[package]
name = "http-studio-infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
async-stream = "0.3.6"
async-trait = "0.1.92"
bytes = "1.12.1"
directories = "6.0.0"
futures-core = "0.3.34"
http-studio-application = { version = "0.1.0", path = "../application" }
http-studio-domain = { version = "0.1.0", path = "../domain" }
reqwest = { version = "0.13.4", default-features = false, features = ["rustls", "http2", "stream", "charset", "gzip", "brotli"] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "fs", "time"] }
url = "2.5.8"

[dev-dependencies]
rusqlite = { version = "0.40.2", features = ["bundled"] }
tempfile = "3.24.0"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
