[package]
name = "http-studio-domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
url = { version = "2.5.8", features = ["serde"] }
